### ISSUE TITLE
Can't connect to solo_pool 0.1.11

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion_miner#27]
When I start the miner (0.1.10), the pool throws the following error:

```
jim@riddles:~/aion/aion_miner/aion_solo_pool$ ./run_quickstart.sh 
20061:C 06 Apr 10:14:21.608 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
20061:C 06 Apr 10:14:21.608 # Redis version=4.0.8, bits=64, commit=a9a5ea05, modified=1, pid=20061, just started
20061:C 06 Apr 10:14:21.608 # Configuration loaded
function verify() { [native code] }
2018-04-06 10:14:24 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-04-06 10:14:25 [Master]	[CLI] CLI listening on port 17117
2018-04-06 10:14:25 [Master]	[PoolSpawner] Spawned 1 pool(s) on 1 thread(s)
function verify() { [native code] }
2018-04-06 10:14:25 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2018-04-06 10:14:25 [Pool]	[aion] (Thread 1) Could not start pool, error with init RPC validateaddress - {"code":-32601,"message":"Method not found"}
2018-04-06 10:14:25 [Pool]	[aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2018-04-06 10:14:25 [Switching]	[Setup] (Thread 1) Switching "switch0" listening for equihash on port 3333 into aion
2018-04-06 10:17:21 [Switching]	[Connect] (Thread 1) Connection to switch0 from ::ffff:127.0.0.1 on 3333 routing to aion
/home/jim/aion/aion_miner/aion_solo_pool/libs/poolWorker.js:279
                            pools[currentPool].getStratumServer().handleNewClient(socket);
                                                                 ^

TypeError: Cannot read property 'handleNewClient' of undefined
    at Server.<anonymous> (/home/jim/aion/aion_miner/aion_solo_pool/libs/poolWorker.js:279:66)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Object.onconnection (net.js:1561:8)
    at onconnection (internal/cluster/child.js:168:12)
    at Worker.onmessage (internal/cluster/child.js:43:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
```

The miner keeps trying to connect, so this error repeats all the time.

**Comment by aion-Ross** [comment]
This behavior usually happens when the kernel is under heavy load the pool receives client connections before it is able to connect to the kernel. 

Could you try stopping the miner temporarily until the pool fully starts? That will usually allow miners to connect properly.
