### ISSUE TITLE
RPC 

### ISSUE THREAD

**Issue by sbglive** [aionnetwork/aion_miner#28]
Dear AION team,

I tried to set up the solo_pool, aion kernel and miner by following the documentation. Though I think something is wrong on the solo_pool as I keep having errors in the logs.

It seems the pool does not connect well to the aion kernel (problem 1), and then there is an error on the pool when the miner connects (problem 2).

What I did:
1. Start the solo_pool
2. Start the aion kernel
3. Start the miner

The solo_pool logs look like:
```bash
6976:C 07 Apr 17:51:21.033 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
6976:C 07 Apr 17:51:21.033 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=6976, just started
6976:C 07 Apr 17:51:21.033 # Configuration loaded
function verify() { [native code] }2018-04-07 17:51:21 [POSIX]     [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised2018-04-07 17:51:21 [Master]    [CLI] CLI listening on port 17117
2018-04-07 17:51:21 [Master]    [PoolSpawner] Spawned 1 pool(s) on 1 thread(s)function verify() { [native code] }
2018-04-07 17:51:21 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2018-04-07 17:51:21 [Pool]      [aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2018-04-07 17:51:21 [Pool]      [aion] (Thread 1) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED 127.0.0.1:8545"}
2018-04-07 17:51:21 [Switching] [Setup] (Thread 1) Switching "switch0" listening for equihash onport 3333 into aion
```

The aion kernel logs look good.
```bash
...
18-04-07 17:54:09.576 INFO  SYNC [sync-ib]: <import-status: node = c1f426, number = 36605, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>
18-04-07 17:54:09.577 INFO  SYNC [sync-ib]: <import-status: node = c1f426, number = 36606, txs = 0, result = IMPORTED_BEST, time elapsed = 1 ms>
...
```

The miner logs:
```bash
...
[17:54:58][0x00007fd173826700] stratum | Connecting to stratum server 127.0.0.1:3333[17:54:58][0x00007fd173826700] stratum | Connected!
[17:54:58][0x00007fd173826700] stratum | read_until: Connection reset by peer
[17:54:58][0x00007fd173826700] stratum | Reconnecting in 3 seconds...
[17:55:01][0x00007fd173826700] stratum | Connecting to stratum server 127.0.0.1:3333
[17:55:01][0x00007fd173826700] stratum | Connected!
[17:55:01][0x00007fd173826700] stratum | read_until: Connection reset by peer
[17:55:01][0x00007fd173826700] stratum | Reconnecting in 3 seconds...
[17:55:04][0x00007fd173826700] stratum | Connecting to stratum server 127.0.0.1:3333
[17:55:04][0x00007fd173826700] stratum | Connected!
[17:55:04][0x00007fd173826700] stratum | read_until: Connection reset by peer
[17:55:04][0x00007fd173826700] stratum | Reconnecting in 3 seconds...
[17:55:06][0x00007fd1748b1740] Speed [15 sec]: 0 I/s, 0 Sols/s
[17:55:07][0x00007fd173826700] stratum | Connecting to stratum server 127.0.0.1:3333
[17:55:07][0x00007fd173826700] stratum | Connected!
[17:55:07][0x00007fd173826700] stratum | read_until: Connection reset by peer
[17:55:07][0x00007fd173826700] stratum | Reconnecting in 3 seconds
...
```

After I turn on the miner, I get this messages on the solo_pool:
```bash
on
/home/xxx/Documents/AION/solo/libs/poolWorker.js:279
                            pools[currentPool].getStratumServer().handleNewClient(socket);
                                                                 ^

TypeError: Cannot read property 'handleNewClient' of undefined
    at Server.<anonymous> (/home/brice/Documents/AION/solo/libs/poolWorker.js:279:66)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Object.onconnection (net.js:1561:8)
    at onconnection (internal/cluster/child.js:168:12)
    at Worker.onmessage (internal/cluster/child.js:43:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
2018-04-07 17:55:58 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...
function verify() { [native code] }
2018-04-07 17:56:00 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2018-04-07 17:56:00 [Pool]      [aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2018-04-07 17:56:00 [Switching] [Setup] (Thread 1) Switching "switch0" listening for equihash onport 3333 into aion
2018-04-07 17:56:00 [Pool]      [aion] (Thread 1) Could not start pool, error with init RPC validateaddress - {"code":-32601,"message":"Method not found"}
2018-04-07 17:56:01 [Switching] [Connect] (Thread 1) Connection to switch0 from ::ffff:127.0.0.1on 3333 routing to aion
/home/xxx/Documents/AION/solo/libs/poolWorker.js:279
                            pools[currentPool].getStratumServer().handleNewClient(socket);
```

Could you please help me solve the issue ?

Thank you in advance,
Ben.

**Comment by aion-Ross** [comment]
Could you try replacing the api-enabled setting in your aion kernel with the following: 

```<apis-enabled>web3,eth,personal,stratum</apis-enabled>```

The errors with the miner are normal when the pool as not been able to connect to the kernel.
