### ISSUE TITLE
Solo pool v0.2.3 setup problem

### ISSUE THREAD

**Issue by proroq4** [aionnetwork/aion_miner#38]
Hello,
i have installed v0.2.3 solo pool and getting this error, could you please point me what am I doing wrong ?
I have unpack release file, run npm install in datadir ,execute ./configure.sh. and run it through the ./run_quickstart. Previous version on the same machine works.
thank you !

dave@ubuntu:/datadir/data/aion/pool023$ ./run_quickstart.sh
11515:C 11 Jan 10:52:20.725 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11515:C 11 Jan 10:52:20.725 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=11515, just started
11515:C 11 Jan 10:52:20.725 # Configuration loaded
function verify() { [native code] }
2019-01-11 10:52:21 [POSIX] [Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2019-01-11 10:52:21 [Master] [CLI] CLI listening on port 17117
2019-01-11 10:52:21 [Master] [PoolSpawner] Spawned 1 pool(s) on 1 thread(s)
function verify() { [native code] }
2019-01-11 10:52:21 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2019-01-11 10:52:21 [Pool] [aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
/datadir/data/aion/pool023/local_modules/stratum-pool/lib/daemon.js:137
result.sort(function(a, b){
^

TypeError: Cannot read property ‘sort’ of null
at /datadir/data/aion/pool023/local_modules/stratum-pool/lib/daemon.js:137:20
at ClientRequest. (/datadir/data/aion/pool023/local_modules/stratum-pool/lib/daemon.js:103:17)
at emitOne (events.js:116:13)
at ClientRequest.emit (events.js:211:7)
at Socket.socketErrorListener (_http_client.js:387:9)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at emitErrorNT (internal/streams/destroy.js:64:8)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
2019-01-11 10:52:21 [Master] [PoolSpawner] Fork 0 died, spawning replacement worker…
function verify() { [native code] }

thanks for help

**Comment by proroq4** [comment]
Hi Ross, 
yes kernel is running v 0.3.2.

**Comment by aion-Ross** [comment]
Only way I'm able to reproduce that error is if the pool is unable to communicate with the kernel.  Could you double check the network settings for the pool and rpc settings for the kernel? If the pool and kernel are running on the same machine you can use 127.0.0.1:8545, if they're on different machines the settings will depend on your network.

Pool settings will be in pool_configs/aion.json and kernel will usually be in mastery/config/config.xml

**Comment by proroq4** [comment]
Hi Ross, 
sorry for delay.  You are right , pool was unable to connect to the kernel. Thanks for poiting me.
