### ISSUE TITLE
npm install fails: "error: no matching function for call"

### ISSUE THREAD

**Issue by g00dnatur3** [aionnetwork/aion_miner#40]
```
../src/binding.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Hash::Copy(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cpp:234:80: error: no matching function for call to ‘v8::Function::NewInstance(const unsigned int&, v8::Local<v8::Value> [1])’
   v8::Local<v8::Object> inst = construct->GetFunction()->NewInstance(argc, argv);
                                                                                ^
In file included from /home/mine/.node-gyp/10.15.3/include/node/node.h:63:0,
                 from ../src/binding.cpp:1:
/home/mine/.node-gyp/10.15.3/include/node/v8.h:3993:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/mine/.node-gyp/10.15.3/include/node/v8.h:3993:44: note:   candidate expects 3 arguments, 2 provided
/home/mine/.node-gyp/10.15.3/include/node/v8.h:3996:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/mine/.node-gyp/10.15.3/include/node/v8.h:3996:44: note:   candidate expects 1 argument, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-const-variable’
binding.target.mk:130: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/mine/aion_miner/aion_solo_pool/local_modules/node-blake2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.8.0-34-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mine/aion_miner/aion_solo_pool/local_modules/node-blake2
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN aion-mining-pool@0.2.1 No repository field.
npm WARN The package moment is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blake2@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blake2@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mine/.npm/_logs/2019-05-11T06_46_25_023Z-debug.log
```

**Comment by g00dnatur3** [comment]
all i did was clone and npm install

ubuntu linux

intel machine
