### ISSUE TITLE
solo_pool incompatible with kernel 0.4.0

### ISSUE THREAD

**Issue by JimVanEeden** [aionnetwork/aion_miner#43]
Using kernel 0.4.0, I can not longer start the solo_pool:

```
2019-05-27 07:24:18 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2019-05-27 07:24:18 [Pool] [aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:137
            result.sort(function(a, b){
                   ^

TypeError: Cannot read property 'sort' of null
    at /home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:137:20
    at ClientRequest.<anonymous> (/home/jim/aion-home/aion_miner/aion_solo_pool/local_modules/stratum-pool/lib/daemon.js:103:17)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
2019-05-27 07:24:18 [Master] [PoolSpawner] Fork 0 died, spawning replacement worker...
```

A fix would be highly appreciated, I don't want to join a mining pool.

**Comment by dipeshnuco** [comment]
@JimVanEeden thanks for raising this issue, we are looking at it.

**Comment by AionJayT** [comment]
Can I know your config settings? the rpc server need to enable it and the ip and port should be match your pool settings.
```
        <rpc active="true" ip="127.0.0.1" port="8545">
            <cors-enabled>false</cors-enabled>
            <!--comma-separated list, APIs available: web3,net,debug,personal,eth,stratum-->
            <apis-enabled>web3,eth,personal,stratum,ops</apis-enabled>
        </rpc>
```

**Comment by JimVanEeden** [comment]
I just used the default config.xml and copied in my previous id and my miner address.

```
<rpc active="false" ip="127.0.0.1" port="8545">
    <cors-enabled>false</cors-enabled>
    <!--comma-separated list, APIs available: web3,net,debug,personal,eth,stratum-->
    <apis-enabled>web3,eth,personal,stratum,ops</apis-enabled>
</rpc>
```

**Comment by AionJayT** [comment]
@JimVanEeden your rpc seervice does not open. Please revise the settings
```rpc active="true"
```
Thanks.

**Comment by JimVanEeden** [comment]
Alright that worked, thanks. That option used to be enabled by default.
