### ISSUE TITLE
buffer.js Type error

### ISSUE THREAD

**Issue by l-derosa** [aionnetwork/aion_miner#44]
Hi all,
the pools start but after a while shows a lot of errors, the miner receives jobs but reports an error (empty jobs?) any hint to solve this issue? 
BTW: also reports a network difficulty of zero ...

2020-04-16 19:18:22 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2020-04-16 19:18:22 [Pool]	[aion] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2020-04-16 19:18:22 [Switching]	[Setup] (Thread 1) Switching "switch0" listening for equihash on port 3333 into aion
s 66
2020-04-16 19:18:22 [Pool]	[aion] (Thread 1) No rewardRecipients have been setup which means no fees will be taken
2020-04-16 19:18:22 [Pool]	[aion] (Thread 1) Network diff of 0 is lower than port 3008 w/ diff 4
2020-04-16 19:18:22 [Pool]	[aion] (Thread 1) Stratum Pool Server Started for aion [NGR] {equihash}
						Network Connected:	Mainnet
						Detected Reward Type:	POW
						Current Block Height:	5838226
						Current Connect Peers:	7
						Current Block Diff:	0.00291596
						Network Difficulty:	0
						Network Hash Rate:	NaN KH
						Stratum Port(s):	3008
						Pool Fee Percent:	0%
						Block polling every:	1000 ms
2020-04-16 19:18:22 [Switching]	[Setup] (equihash) Setting proxy difficulties after pool start
2020-04-16 19:18:58 [Pool]	[aion] (Thread 1) Block notification via RPC polling
2020-04-16 19:19:19 [Pool]	[aion] (Thread 1) Block notification via RPC polling

**buffer.js:183
    throw new TypeError(kFromErrorMsg);
    ^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.**

    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at Object.exports.bignumFromBitsHex (/home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/util.js:371:20)
    at new BlockTemplate (/home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/blockTemplate.js:60:14)
    at JobManager.processTemplate (/home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/jobManager.js:191:32)
    at /home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/pool.js:601:62
    at itemFinished (/home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/daemon.js:162:36)
    at /home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/daemon.js:175:17
    at parseJson (/home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/home/luh/builddir/aion-solo-pool-0.2.3-2019-01-04/node_modules/stratum-pool/lib/daemon.js:95:17)
2020-04-16 19:19:54 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...
function verify() { [native code] }

**Comment by AionMiner** [comment]
This version of the pool software (solo) is no longer compatible with the latest (mandatory) OAN kernel version. If you wish to run your own pool you will need to use the [aion_pool2](https://github.com/aionnetwork/aion_pool2) implementation.
