### ISSUE TITLE
Error: Cannot find module 'nan'

### ISSUE THREAD

**Issue by rnkhouse** [aionnetwork/aion_miner#5]
While running `node-gyp configure` command inside `local_modules/equihashverify` directory:

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:410:26)
    at node.js:578:27
    at nextTickCallbackWith0Args (node.js:419:9)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.0-1007-azure
gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /home/ronak/aion_miner/aion_solo_pool/local_modules/equihashverify
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Solution: `npm install nan` and then run the specified command.

**Comment by rnkhouse** [comment]
Solution: npm install nan and then run the specified command.
